package frc.robot.util.binrw;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Excludes a field or record component from binary serialization generated by {@link Binrw}.
 *
 * <p>
 * The annotated field will not be written to the stream by the generated writer, and the generated
 * reader will not attempt to read a value for it. For classes, the field is simply left at its
 * default value after construction. The constructor called by the reader must therefore not require
 * the ignored field as a parameter.
 *
 * <p>
 * Example:
 *
 * <pre>
 * {
 *     &#64;code
 *     &#64;Binrw
 *     public class Sensor {
 *         public double voltage;
 *         @BrwIgnore
 *         public double debugValue;
 *
 *         public Sensor(double voltage) {} // constructor does not take debugValue
 *     }
 *     // only 'voltage' appears in SensorReader / SensorWriter
 * }
 * </pre>
 *
 * @see Binrw
 */
@Target({ElementType.FIELD, ElementType.RECORD_COMPONENT})
@Retention(RetentionPolicy.SOURCE)
public @interface BrwIgnore {
}
